version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml

  inventory-service:
    build:
      context: ./inventory-service
    image: practica-inventory-service
    ports:
      - "8000:8000"
    networks:
      - app-network 

  orders-service:
    build:
      context: ./orders-service
    image: practica-orders-service
    ports:
      - "8001:8001"
    networks:
      - app-network
      
  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki

networks:
  app-network:
    driver: bridge
