version: '3.8'
services:
  service1:
    build:
      context: ./service1
    ports:
      - "3000:3000"
    depends_on:
      - service2
    networks:
      - app-network

  service2:
    build:
      context: ./service2
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
