global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8000']

  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:8001']
